routes:
  - route_id: 0001
    path_prefix: /api/user
    upstream_URL: http://mock-upstream:8000
    timeout: 30
    strip_prefix: true
    middleware_names:
      - auth
      - rate-limiter
      - circuit-breaker
    metadata: {}

  - route_id: 0002
    path_prefix: /api/user/admin
    upstream_URL: http://mock-upstream:8000
    timeout: 60
    strip_prefix: true
    middleware_names:
      - auth
      - rate-limiter
      - circuit-breaker
    metadata: {}
